<a href="https://colab.research.google.com/github/alvumu/TGINE/blob/main/Practica2/Practica2TGINE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install google-api-python-client


In [2]:
from googleapiclient.discovery import build

# Tu clave de API de YouTube

API_KEY = 'AIzaSyA4GHuBPJLKi1YzUoNslC87dfycuvl5eU4'

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Nombre del canal o URL del canal

channelsNames = ['NUDEPROJECT', 'TheWildProject', 'worldcast_', 'EclecticosWorldwide', 'offsiders.project', 'Loquetudigas', 'Laplacitaamarilla', 'SMAE_Podcast', 'tengounplanpodcast', 'spicy4tuna']
channelIdName = dict()
for name in channelsNames :
  channelIdName[name] = []
  # Utiliza la API de búsqueda para obtener información del canal
  channel_info = youtube.search().list(
                part='snippet',
                maxResults=1,
                q=name,
                type='channel'
        ).execute()

  channel_id = channel_info['items'][0]['id'].get("channelId")
  channelIdName[name].append(channel_id)
print(channelIdName)

{'NUDEPROJECT': ['UCmCg86gXHnROv4ZIXbdGWlg'], 'TheWildProject': ['UCBYyJBCtCvgqA4NwtoPMwpQ'], 'worldcast_': ['UCuDm45jKrsTeEpx7BayVaiw'], 'EclecticosWorldwide': ['UC5a_WZZcGxUMj7_ife0V0lQ'], 'offsiders.project': ['UCOiqjYtg2bcFqCaQK-eWVtw'], 'Loquetudigas': ['UCcpOe_g8sfr2GSoLZISy6yA'], 'Laplacitaamarilla': ['UCFCJ421DAUzG_F_2eFWEfjA'], 'SMAE_Podcast': ['UC63B0Nnt7KE1d6EEUp-cB8Q'], 'tengounplanpodcast': ['UCJFP-5V2-0BFeVmKifG0H_Q'], 'spicy4tuna': ['UCUWDBUEo1YFTzZnBV1aFDBw']}


In [3]:
from googleapiclient.discovery import build
from google.colab import files
import pandas as pd


# Lista para almacenar detalles de canales
data = []


# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

for channel_name, channel_id in channelIdName.items():
    # Obtener información del canal
    channel_info = youtube.channels().list(
        part='snippet',
        id=channel_id
    ).execute()

    # Si se encontró información para el canal
    if 'items' in channel_info and len(channel_info['items']) > 0:
        # Obtener detalles del canal
        snippet = channel_info['items'][0]['snippet']
        title = snippet.get('title', '')
        description = snippet.get('description', '')
        published_at = snippet.get('publishedAt', '')

        # Agregar detalles del canal a la lista de datos
        data.append([channel_name, channel_id[0], title, description, published_at,"Podcast"])

# Crear un DataFrame con los detalles de los canales
columns = ['Nombre', 'ID', 'Título', 'Descripción', 'FechaCreacion', 'Tipo']
dfPodcast = pd.DataFrame(data, columns=columns)

# Mostrar el DataFrame
print(dfPodcast)

                Nombre                        ID                Título  \
0          NUDEPROJECT  UCmCg86gXHnROv4ZIXbdGWlg          NUDE PROJECT   
1       TheWildProject  UCBYyJBCtCvgqA4NwtoPMwpQ      The Wild Project   
2           worldcast_  UCuDm45jKrsTeEpx7BayVaiw             WORLDCA$T   
3  EclecticosWorldwide  UC5a_WZZcGxUMj7_ife0V0lQ  Eclécticos Worldwide   
4    offsiders.project  UCOiqjYtg2bcFqCaQK-eWVtw             Offsiders   
5         Loquetudigas  UCcpOe_g8sfr2GSoLZISy6yA          Alex Fidalgo   
6    Laplacitaamarilla  UCFCJ421DAUzG_F_2eFWEfjA   La Placita Amarilla   
7         SMAE_Podcast  UC63B0Nnt7KE1d6EEUp-cB8Q    Sin Miedo Al Éxito   
8   tengounplanpodcast  UCJFP-5V2-0BFeVmKifG0H_Q         Tengo un Plan   
9           spicy4tuna  UCUWDBUEo1YFTzZnBV1aFDBw            spicy4tuna   

                                         Descripción  \
0  Alex Benlloch & Bruno Casanovas, fundadores de...   
1  CADA MARTES Y JUEVES NUEVOS EPISODIOS.\nBienve...   
2  Hosted by: Ped

In [4]:
from googleapiclient.discovery import build
import json

# Inserta tus credenciales de la API de YouTube aquí
API_KEY = 'AIzaSyA4GHuBPJLKi1YzUoNslC87dfycuvl5eU4'

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Lista de canales y sus IDs


# Recorrer el DataFrame por filas usando iterrows()
for indice, canal in dfPodcast.iterrows():
    # Obtener los 100 videos más vistos del canal
    videos = []
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video'
    )
    response = request.execute()


    # Agrega los primeros 50 videos a la lista
    videos.extend(response['items'])

#  Verifica si hay una segunda página de resultados
    if 'nextPageToken' in response:
        next_page_token = response['nextPageToken']

    # Realiza una nueva solicitud para obtener los siguientes 50 videos
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video',
        pageToken=next_page_token
    )
    response = request.execute()

    # Agrega los siguientes 50 videos a la lista
    videos.extend(response['items'])
    response = request.execute()
    print("------Procesando : "+canal['Nombre']+" ---------")

    # Estructurar los datos en el formato deseado
    videosData = []

    for item in videos:
        # Obtener los comentarios del video

        video_id = item['id']['videoId']
        comments_request = youtube.commentThreads().list(
            part='snippet',
            videoId=video_id,
            maxResults=15  # Puedes ajustar este número según tus necesidades
        )
        comments_response = comments_request.execute()

        comments = []
        for comment_item in comments_response['items']:
            comment = {
                "user": comment_item['snippet']['topLevelComment']['snippet']['authorDisplayName'],
                "comment": comment_item['snippet']['topLevelComment']['snippet']['textDisplay'],
                "sentiment": ""  # Puedes agregar análisis de sentimiento si lo deseas
            }
            comments.append(comment)

        video_data = {
            "date": item['snippet']['publishedAt'],
            "title": item['snippet']['title'],
            "description": item['snippet']['description'],
            "comments": comments
        }
        videosData.append(video_data)

    # Crear el diccionario con la información del canal y videos
    canal_info = {
        "channel": canal['Nombre'],
        "type": canal['Tipo'],
        "videos": videosData
    }
    print(" Procesados ", len(videosData))


    # Guardar los datos en un archivo JSON
    nombre_archivo = f"{canal['Nombre']}.json"
    with open(nombre_archivo, 'w', encoding='utf-8') as file:
        json.dump(canal_info, file, indent=4, ensure_ascii=False)

------Procesando : NUDEPROJECT ---------
 Procesados  100
------Procesando : TheWildProject ---------
 Procesados  100
------Procesando : worldcast_ ---------
 Procesados  100
------Procesando : EclecticosWorldwide ---------
 Procesados  100
------Procesando : offsiders.project ---------
 Procesados  100
------Procesando : Loquetudigas ---------
 Procesados  100
------Procesando : Laplacitaamarilla ---------
 Procesados  100
------Procesando : SMAE_Podcast ---------
 Procesados  100
------Procesando : tengounplanpodcast ---------
 Procesados  100
------Procesando : spicy4tuna ---------
 Procesados  100


In [5]:
from googleapiclient.discovery import build

API_KEY = 'AIzaSyDIWwxlFxTsZB9W25eSG3PDglyqbBiXHL8'

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Nombre del canal o URL del canal

channelsNames = ['QuantumFracture', 'doctorfision', 'ElRobotdePlaton', 'IFTMadrid', 'CienciaDeSofa', 'Lahiperactina', 'CdeCiencia', 'codificandobits', 'Derivando', 'DateunVoltio']
channelIdName = dict()
for name in channelsNames :
  channelIdName[name] = []
  # Utiliza la API de búsqueda para obtener información del canal
  channel_info = youtube.search().list(
                part='snippet',
                maxResults=1,
                q=name,
                type='channel'
        ).execute()

  channel_id = channel_info['items'][0]['id'].get("channelId")
  channelIdName[name].append(channel_id)
print(channelIdName)

{'QuantumFracture': ['UCbdSYaPD-lr1kW27UJuk8Pw'], 'doctorfision': ['UCEQXxiYxNZbym9Fad7-n2Lg'], 'ElRobotdePlaton': ['UCaVPhFg-Ax873wvhbNitsrQ'], 'IFTMadrid': ['UCk195x4zYdMx4LhqEwhcPng'], 'CienciaDeSofa': ['UCMbQbVilo-nezMvwf1BZfAA'], 'Lahiperactina': ['UCV5G678sZwW5IcF3pCfRbHQ'], 'CdeCiencia': ['UC52hytXteCKmuOzMViTK8_w'], 'codificandobits': ['UCFVF0MpD1lNdU5VL3Pz67Yw'], 'Derivando': ['UCH-Z8ya93m7_RD02WsCSZYA'], 'DateunVoltio': ['UCns-8DssCBba7M4nu7wk7Aw']}


In [7]:
from googleapiclient.discovery import build
from google.colab import files
import pandas as pd


# Lista para almacenar detalles de canales
data = []

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

for channel_name, channel_id in channelIdName.items():
    # Obtener información del canal
    channel_info = youtube.channels().list(
        part='snippet',
        id=channel_id
    ).execute()

    # Si se encontró información para el canal
    if 'items' in channel_info and len(channel_info['items']) > 0:
        # Obtener detalles del canal
        snippet = channel_info['items'][0]['snippet']
        title = snippet.get('title', '')
        description = snippet.get('description', '')
        published_at = snippet.get('publishedAt', '')

        # Agregar detalles del canal a la lista de datos
        data.append([channel_name, channel_id[0], title, description, published_at, "Ciencia"])

dfCiencia = pd.DataFrame(data, columns=columns)


In [8]:
from googleapiclient.discovery import build
import json

# Inserta tus credenciales de la API de YouTube aquí
API_KEY = 'AIzaSyDIWwxlFxTsZB9W25eSG3PDglyqbBiXHL8'

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Lista de canales y sus IDs


# Recorrer el DataFrame por filas usando iterrows()
for indice, canal in dfCiencia.iterrows():
    # Obtener los 100 videos más vistos del canal
    videos = []
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video'
    )
    response = request.execute()


    # Agrega los primeros 50 videos a la lista
    videos.extend(response['items'])

#  Verifica si hay una segunda página de resultados
    if 'nextPageToken' in response:
        next_page_token = response['nextPageToken']

    # Realiza una nueva solicitud para obtener los siguientes 50 videos
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video',
        pageToken=next_page_token
    )
    response = request.execute()

    # Agrega los siguientes 50 videos a la lista
    videos.extend(response['items'])
    response = request.execute()
    print("------Procesando : "+canal['Nombre']+" ---------")

    # Estructurar los datos en el formato deseado
    videosData = []

    for item in videos:
        # Obtener los comentarios del video

        video_id = item['id']['videoId']
        comments_request = youtube.commentThreads().list(
            part='snippet',
            videoId=video_id,
            maxResults=15  # Puedes ajustar este número según tus necesidades
        )
        comments_response = comments_request.execute()

        comments = []
        for comment_item in comments_response['items']:
            comment = {
                "user": comment_item['snippet']['topLevelComment']['snippet']['authorDisplayName'],
                "comment": comment_item['snippet']['topLevelComment']['snippet']['textDisplay'],
                "sentiment": ""  # Puedes agregar análisis de sentimiento si lo deseas
            }
            comments.append(comment)

        video_data = {
            "date": item['snippet']['publishedAt'],
            "title": item['snippet']['title'],
            "description": item['snippet']['description'],
            "comments": comments
        }
        videosData.append(video_data)

    # Crear el diccionario con la información del canal y videos
    canal_info = {
        "channel": canal['Nombre'],
        "type": canal['Tipo'],
        "videos": videosData
    }
    print(" Procesados ", len(videosData))


    # Guardar los datos en un archivo JSON
    nombre_archivo = f"{canal['Nombre']}.json"
    with open(nombre_archivo, 'w', encoding='utf-8') as file:
        json.dump(canal_info, file, indent=4, ensure_ascii=False)

------Procesando : QuantumFracture ---------
 Procesados  100
------Procesando : doctorfision ---------
 Procesados  100
------Procesando : ElRobotdePlaton ---------
 Procesados  100
------Procesando : IFTMadrid ---------
 Procesados  100
------Procesando : CienciaDeSofa ---------
 Procesados  100
------Procesando : Lahiperactina ---------
 Procesados  100
------Procesando : CdeCiencia ---------
 Procesados  100
------Procesando : codificandobits ---------
 Procesados  100
------Procesando : Derivando ---------
 Procesados  100
------Procesando : DateunVoltio ---------
 Procesados  100


In [12]:
from googleapiclient.discovery import build

API_KEY = "AIzaSyB579rVu_fku0ueVHs3LaM_SdbWP7tPsl4"
# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Nombre del canal o URL del canal

channelsNames = ['espndeportes', 'mundomaldini', 'Lamediainglesa', 'Nicfut11', 'premierleague', 'Delantero09', 'LaLiga', 'ProyectoFutbolteca', 'javifreestyle', 'memoriasdelfutbol']
channelIdName = dict()
for name in channelsNames :
  channelIdName[name] = []
  # Utiliza la API de búsqueda para obtener información del canal
  channel_info = youtube.search().list(
                part='snippet',
                maxResults=1,
                q=name,
                type='channel'
        ).execute()

  channel_id = channel_info['items'][0]['id'].get("channelId")
  channelIdName[name].append(channel_id)
print(channelIdName)

{'espndeportes': ['UC08mnbiC4FykqpHqbEWgFcg'], 'mundomaldini': ['UCcrBhhQdWjJjjLyrOvYzMaA'], 'Lamediainglesa': ['UC2V8vo8d3i-XQR-JcrmwwFA'], 'Nicfut11': ['UC7I9AdGpKGe1mKBFAZsFZaw'], 'premierleague': ['UCG5qGWdu8nIRZqJ_GgDwQ-w'], 'Delantero09': ['UCZBJjyp-QbQKvmFkG-ltmvQ'], 'LaLiga': ['UCTv-XvfzLX3i4IGWAm4sbmA'], 'ProyectoFutbolteca': ['UC9KpWygLriBpKk0Vyb3cjLQ'], 'javifreestyle': ['UCDH0QdbNAODoidTx502EDtg'], 'memoriasdelfutbol': ['UCWNv6vx6WOTN91XGT5OHVXg']}


In [13]:
from googleapiclient.discovery import build
from google.colab import files
import pandas as pd


# Lista para almacenar detalles de canales
data = []



# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

for channel_name, channel_id in channelIdName.items():
    # Obtener información del canal
    channel_info = youtube.channels().list(
        part='snippet',
        id=channel_id
    ).execute()

    # Si se encontró información para el canal
    if 'items' in channel_info and len(channel_info['items']) > 0:
        # Obtener detalles del canal
        snippet = channel_info['items'][0]['snippet']
        title = snippet.get('title', '')
        description = snippet.get('description', '')
        published_at = snippet.get('publishedAt', '')

        # Agregar detalles del canal a la lista de datos
        data.append([channel_name, channel_id[0], title, description, published_at, "Futbol"])

dfFutbol = pd.DataFrame(data, columns=columns)

In [14]:
from googleapiclient.discovery import build
import json

# Inserta tus credenciales de la API de YouTube aquí
API_KEY = 'AIzaSyB579rVu_fku0ueVHs3LaM_SdbWP7tPsl4'

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Lista de canales y sus IDs


# Recorrer el DataFrame por filas usando iterrows()
for indice, canal in dfFutbol.iterrows():
    # Obtener los 100 videos más vistos del canal
    videos = []
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video'
    )
    response = request.execute()


    # Agrega los primeros 50 videos a la lista
    videos.extend(response['items'])

#  Verifica si hay una segunda página de resultados
    if 'nextPageToken' in response:
        next_page_token = response['nextPageToken']

    # Realiza una nueva solicitud para obtener los siguientes 50 videos
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video',
        pageToken=next_page_token
    )
    response = request.execute()

    # Agrega los siguientes 50 videos a la lista
    videos.extend(response['items'])
    response = request.execute()
    print("------Procesando : "+canal['Nombre']+" ---------")

    # Estructurar los datos en el formato deseado
    videosData = []

    for item in videos:
        # Obtener los comentarios del video

        video_id = item['id']['videoId']
        comments_request = youtube.commentThreads().list(
            part='snippet',
            videoId=video_id,
            maxResults=15  # Puedes ajustar este número según tus necesidades
        )
        comments_response = comments_request.execute()

        comments = []
        for comment_item in comments_response['items']:
            comment = {
                "user": comment_item['snippet']['topLevelComment']['snippet']['authorDisplayName'],
                "comment": comment_item['snippet']['topLevelComment']['snippet']['textDisplay'],
                "sentiment": ""  # Puedes agregar análisis de sentimiento si lo deseas
            }
            comments.append(comment)

        video_data = {
            "date": item['snippet']['publishedAt'],
            "title": item['snippet']['title'],
            "description": item['snippet']['description'],
            "comments": comments
        }
        videosData.append(video_data)

    # Crear el diccionario con la información del canal y videos
    canal_info = {
        "channel": canal['Nombre'],
        "type": canal['Tipo'],
        "videos": videosData
    }
    print(" Procesados ", len(videosData))


    # Guardar los datos en un archivo JSON
    nombre_archivo = f"{canal['Nombre']}.json"
    with open(nombre_archivo, 'w', encoding='utf-8') as file:
        json.dump(canal_info, file, indent=4, ensure_ascii=False)


------Procesando : espndeportes ---------
 Procesados  100
------Procesando : mundomaldini ---------
 Procesados  100
------Procesando : Lamediainglesa ---------
 Procesados  100
------Procesando : Nicfut11 ---------
 Procesados  100
------Procesando : premierleague ---------
 Procesados  100
------Procesando : Delantero09 ---------
 Procesados  100
------Procesando : LaLiga ---------
 Procesados  100
------Procesando : ProyectoFutbolteca ---------
 Procesados  100
------Procesando : javifreestyle ---------
 Procesados  100
------Procesando : memoriasdelfutbol ---------
 Procesados  100


In [17]:
from google.colab import files
import os

folder_path = '/content/'

for file in os.listdir(folder_path):
    if file.endswith('.json'):  # Verifica si el archivo es de tipo JSON
        files.download(folder_path + file)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
import pandas as pd
import json
from sklearn.model_selection import train_test_split

# Lista para almacenar los datos
data = []

# Leer los archivos JSON y cargar los datos
for file in os.listdir(folder_path):
    if file.endswith('.json'):  # Verifica si el archivo es de tipo JSON
      with open(file, 'r') as json_file:
          json_data = json.load(json_file)
          channel = json_data["channel"]
          type_channel = json_data['type']
          videos = json_data['videos']
          for video in videos:
                  title = video['title']
                  description = video['description']
                  data.append({'Canal': channel, 'Tipo de Canal': type_channel, 'Título': title, 'Descripción': description})

# Crear un DataFrame de Pandas
df = pd.DataFrame(data)

print(df)



In [ ]:
import pandas as pd

# Supongamos que tienes tu DataFrame llamado df con las columnas 'Canal', 'Tipo de Canal', 'Título' y 'Descripción'

# Identificar los canales únicos para cada tipo de canal
channels_futbol = df[df['Tipo de Canal'] == 'Futbol']['Canal'].unique()
channels_podcast = df[df['Tipo de Canal'] == 'Podcast']['Canal'].unique()
channels_ciencia = df[df['Tipo de Canal'] == 'Ciencia']['Canal'].unique()

# Dividir los canales en entrenamiento y prueba (7 canales para entrenamiento, 3 para prueba)
channels_train_futbol = channels_futbol[:7]
canales_test_futbol = channels_futbol[7:]

channels_train_podcast = channels_podcast[:7]
channels_test_podcast = channels_podcast[7:]

channels_train_ciencia = channels_ciencia[:7]
channels_test_ciencia = channels_ciencia[7:]

# Filtrar los datos para obtener conjuntos separados de entrenamiento y prueba
train_data = df[(df['Canal'].isin(channels_train_futbol)) | (df['Canal'].isin(channels_train_podcast)) | (df['Canal'].isin(channels_train_ciencia)) ]
test_data = df[(df['Canal'].isin(canales_test_futbol)) | (df['Canal'].isin(channels_test_podcast)) | (df['Canal'].isin(channels_test_ciencia))]

# Verificar la distribución de canales en los conjuntos de entrenamiento y prueba
print("Canales en datos de entrenamiento:")
print(train_data['Canal'].value_counts())

print("\nCanales en datos de prueba:")
print(test_data['Canal'].value_counts())



In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

# Vectorización de texto
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(train_data['Descripción'])
X_test_vec = vectorizer.transform(test_data['Descripción'])

# Definir varios modelos
models = {
    'Random Forest': RandomForestClassifier(),
    'SVM': SVC(),
    'Naive Bayes': MultinomialNB(),
    'Logistic Regression': LogisticRegression(),
    'Gradient Boosting Machine': GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, max_depth=3, random_state=42)
}

# Entrenamiento y evaluación de varios modelos
for name, model in models.items():
    print(f"Entrenando modelo: {name}")
    model.fit(X_train_vec, train_data['Tipo de Canal'])

    # Predicciones
    y_pred = model.predict(X_test_vec)

    # Evaluación del modelo
    accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred)
    print(f"Precisión del modelo {name}: {accuracy}")

    conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred)
    print(f"Matriz de Confusión {name}:\n{conf_matrix}")

    class_report = classification_report(test_data['Tipo de Canal'], y_pred)
    print(f"Reporte de Clasificación {name}:\n{class_report}")
    print("--------------------------------------------------")


Entrenando modelo: Random Forest
Precisión del modelo Random Forest: 0.6855555555555556
Matriz de Confusión Random Forest:
[[274  10  16]
 [131 163   6]
 [ 89  31 180]]
Reporte de Clasificación Random Forest:
              precision    recall  f1-score   support

     Ciencia       0.55      0.91      0.69       300
      Futbol       0.80      0.54      0.65       300
     Podcast       0.89      0.60      0.72       300

    accuracy                           0.69       900
   macro avg       0.75      0.69      0.68       900
weighted avg       0.75      0.69      0.68       900

--------------------------------------------------
Entrenando modelo: SVM
Precisión del modelo SVM: 0.67
Matriz de Confusión SVM:
[[271  26   3]
 [119 179   2]
 [ 82  65 153]]
Reporte de Clasificación SVM:
              precision    recall  f1-score   support

     Ciencia       0.57      0.90      0.70       300
      Futbol       0.66      0.60      0.63       300
     Podcast       0.97      0.51      0.

In [45]:
import transformers
from transformers import AutoModelForSequenceClassification

path_sentiment_model = 'finiteautomata/beto-sentiment-analysis'

# Obtenemos el tokenizer
tokenizer = transformers.AutoTokenizer.from_pretrained (path_sentiment_model)
# Obtenemos el modelo para análisis de sentimientos que tiene 3 etiquetas: positivo, negativo y neutro
sentiment_model = AutoModelForSequenceClassification.from_pretrained(path_sentiment_model)




tokenizer_config.json:   0%|          | 0.00/528 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/841 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/242k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/481k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/67.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


pytorch_model.bin:   0%|          | 0.00/440M [00:00<?, ?B/s]

In [48]:
import torch

# Leer los archivos JSON y cargar los datos
for file in os.listdir(folder_path):
    if file.endswith('.json'):  # Verifica si el archivo es de tipo JSON
      with open(file, 'r', encoding="utf-8") as json_file:
          json_data = json.load(json_file)
          videos = json_data['videos']
          videos_data = []
          for video in videos:
            comments = []
            for comment in video["comments"]:
                inputs = tokenizer(comment['comment'], return_tensors="pt")
                with torch.no_grad():
                  logits = sentiment_model(**inputs).logits
                predicted_class_id = logits.argmax().item()
                prediction= sentiment_model.config.id2label[predicted_class_id]
                comment = {
                    "user": comment["user"],
                    "comment": comment["comment"],
                    "sentiment": prediction  # Puedes agregar análisis de sentimiento si lo deseas
                }
                comments.append(comment)
            video_data = {
            "date": video["date"],
            "title": video["title"],
            "description": video["description"],
            "comments": comments
            }
            videos_data.append(video_data)

    # Crear el diccionario con la información del canal y videos
          canal_info = {
            "channel": json_data['channel'],
            "type": json_data['type'],
            "videos": videosData
        }

    # Guardar los datos en un archivo JSON
      with open(file, 'w', encoding='utf-8') :
          json.dump(canal_info, file, indent=4, ensure_ascii=False)


Token indices sequence length is longer than the specified maximum sequence length for this model (959 > 512). Running this sequence through the model will result in indexing errors


RuntimeError: ignored