<a href="https://colab.research.google.com/github/alvumu/TGINE/blob/main/Practica2/Practica2TGINE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install google-api-python-client


In [ ]:
from googleapiclient.discovery import build

# Tu clave de API de YouTube

API_KEY = 'AIzaSyA4GHuBPJLKi1YzUoNslC87dfycuvl5eU4'

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Nombre del canal o URL del canal

channelsNames = ['NUDEPROJECT', 'TheWildProject', 'worldcast_', 'EclecticosWorldwide', 'offsiders.project', 'Loquetudigas', 'Laplacitaamarilla', 'SMAE_Podcast', 'tengounplanpodcast', 'spicy4tuna']
channelIdName = dict()
for name in channelsNames :
  channelIdName[name] = []
  # Utiliza la API de búsqueda para obtener información del canal
  channel_info = youtube.search().list(
                part='snippet',
                maxResults=1,
                q=name,
                type='channel'
        ).execute()

  channel_id = channel_info['items'][0]['id'].get("channelId")
  channelIdName[name].append(channel_id)
print(channelIdName)

{'NUDEPROJECT': ['UCmCg86gXHnROv4ZIXbdGWlg'], 'TheWildProject': ['UCBYyJBCtCvgqA4NwtoPMwpQ'], 'worldcast_': ['UCuDm45jKrsTeEpx7BayVaiw'], 'EclecticosWorldwide': ['UC5a_WZZcGxUMj7_ife0V0lQ'], 'offsiders.project': ['UCOiqjYtg2bcFqCaQK-eWVtw'], 'Loquetudigas': ['UCcpOe_g8sfr2GSoLZISy6yA'], 'Laplacitaamarilla': ['UCFCJ421DAUzG_F_2eFWEfjA'], 'SMAE_Podcast': ['UC63B0Nnt7KE1d6EEUp-cB8Q'], 'tengounplanpodcast': ['UCJFP-5V2-0BFeVmKifG0H_Q'], 'spicy4tuna': ['UCUWDBUEo1YFTzZnBV1aFDBw']}


In [ ]:
from googleapiclient.discovery import build
from google.colab import files
import pandas as pd


# Lista para almacenar detalles de canales
data = []


# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

for channel_name, channel_id in channelIdName.items():
    # Obtener información del canal
    channel_info = youtube.channels().list(
        part='snippet',
        id=channel_id
    ).execute()

    # Si se encontró información para el canal
    if 'items' in channel_info and len(channel_info['items']) > 0:
        # Obtener detalles del canal
        snippet = channel_info['items'][0]['snippet']
        title = snippet.get('title', '')
        description = snippet.get('description', '')
        published_at = snippet.get('publishedAt', '')

        # Agregar detalles del canal a la lista de datos
        data.append([channel_name, channel_id[0], title, description, published_at,"Podcast"])

# Crear un DataFrame con los detalles de los canales
columns = ['Nombre', 'ID', 'Título', 'Descripción', 'FechaCreacion', 'Tipo']
dfPodcast = pd.DataFrame(data, columns=columns)

# Mostrar el DataFrame
print(dfPodcast)

                Nombre                        ID                Título  \
0          NUDEPROJECT  UCmCg86gXHnROv4ZIXbdGWlg          NUDE PROJECT   
1       TheWildProject  UCBYyJBCtCvgqA4NwtoPMwpQ      The Wild Project   
2           worldcast_  UCuDm45jKrsTeEpx7BayVaiw             WORLDCA$T   
3  EclecticosWorldwide  UC5a_WZZcGxUMj7_ife0V0lQ  Eclécticos Worldwide   
4    offsiders.project  UCOiqjYtg2bcFqCaQK-eWVtw             Offsiders   
5         Loquetudigas  UCcpOe_g8sfr2GSoLZISy6yA          Alex Fidalgo   
6    Laplacitaamarilla  UCFCJ421DAUzG_F_2eFWEfjA   La Placita Amarilla   
7         SMAE_Podcast  UC63B0Nnt7KE1d6EEUp-cB8Q    Sin Miedo Al Éxito   
8   tengounplanpodcast  UCJFP-5V2-0BFeVmKifG0H_Q         Tengo un Plan   
9           spicy4tuna  UCUWDBUEo1YFTzZnBV1aFDBw            spicy4tuna   

                                         Descripción  \
0  Alex Benlloch & Bruno Casanovas, fundadores de...   
1  CADA MARTES Y JUEVES NUEVOS EPISODIOS.\nBienve...   
2  Hosted by: Ped

In [ ]:
from googleapiclient.discovery import build
import json

# Inserta tus credenciales de la API de YouTube aquí
API_KEY = 'AIzaSyA4GHuBPJLKi1YzUoNslC87dfycuvl5eU4'

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Lista de canales y sus IDs


# Recorrer el DataFrame por filas usando iterrows()
for indice, canal in dfPodcast.iterrows():
    # Obtener los 100 videos más vistos del canal
    videos = []
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video'
    )
    response = request.execute()


    # Agrega los primeros 50 videos a la lista
    videos.extend(response['items'])

#  Verifica si hay una segunda página de resultados
    if 'nextPageToken' in response:
        next_page_token = response['nextPageToken']

    # Realiza una nueva solicitud para obtener los siguientes 50 videos
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video',
        pageToken=next_page_token
    )
    response = request.execute()

    # Agrega los siguientes 50 videos a la lista
    videos.extend(response['items'])
    response = request.execute()
    print("------Procesando : "+canal['Nombre']+" ---------")

    # Estructurar los datos en el formato deseado
    videosData = []

    for item in videos:
        # Obtener los comentarios del video

        video_id = item['id']['videoId']
        comments_request = youtube.commentThreads().list(
            part='snippet',
            videoId=video_id,
            maxResults=15  # Puedes ajustar este número según tus necesidades
        )
        comments_response = comments_request.execute()

        comments = []
        for comment_item in comments_response['items']:
            comment = {
                "user": comment_item['snippet']['topLevelComment']['snippet']['authorDisplayName'],
                "comment": comment_item['snippet']['topLevelComment']['snippet']['textDisplay'],
                "sentiment": ""  # Puedes agregar análisis de sentimiento si lo deseas
            }
            comments.append(comment)

        video_data = {
            "date": item['snippet']['publishedAt'],
            "title": item['snippet']['title'],
            "description": item['snippet']['description'],
            "comments": comments
        }
        videosData.append(video_data)

    # Crear el diccionario con la información del canal y videos
    canal_info = {
        "channel": canal['Nombre'],
        "type": canal['Tipo'],
        "videos": videosData
    }
    print(" Procesados ", len(videosData))


    # Guardar los datos en un archivo JSON
    nombre_archivo = f"{canal['Nombre']}.json"
    with open(nombre_archivo, 'w', encoding='utf-8') as file:
        json.dump(canal_info, file, indent=4, ensure_ascii=False)

------Procesando : NUDEPROJECT ---------
 Procesados  100
------Procesando : TheWildProject ---------
 Procesados  100
------Procesando : worldcast_ ---------
 Procesados  100
------Procesando : EclecticosWorldwide ---------
 Procesados  100
------Procesando : offsiders.project ---------
 Procesados  100
------Procesando : Loquetudigas ---------
 Procesados  100
------Procesando : Laplacitaamarilla ---------
 Procesados  100
------Procesando : SMAE_Podcast ---------
 Procesados  100
------Procesando : tengounplanpodcast ---------
 Procesados  100
------Procesando : spicy4tuna ---------
 Procesados  100


In [ ]:
from googleapiclient.discovery import build

API_KEY = 'AIzaSyDIWwxlFxTsZB9W25eSG3PDglyqbBiXHL8'

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Nombre del canal o URL del canal

channelsNames = ['QuantumFracture', 'doctorfision', 'ElRobotdePlaton', 'IFTMadrid', 'CienciaDeSofa', 'Lahiperactina', 'CdeCiencia', 'codificandobits', 'Derivando', 'DateunVoltio']
channelIdName = dict()
for name in channelsNames :
  channelIdName[name] = []
  # Utiliza la API de búsqueda para obtener información del canal
  channel_info = youtube.search().list(
                part='snippet',
                maxResults=1,
                q=name,
                type='channel'
        ).execute()

  channel_id = channel_info['items'][0]['id'].get("channelId")
  channelIdName[name].append(channel_id)
print(channelIdName)

{'QuantumFracture': ['UCbdSYaPD-lr1kW27UJuk8Pw'], 'doctorfision': ['UCEQXxiYxNZbym9Fad7-n2Lg'], 'ElRobotdePlaton': ['UCaVPhFg-Ax873wvhbNitsrQ'], 'IFTMadrid': ['UCk195x4zYdMx4LhqEwhcPng'], 'CienciaDeSofa': ['UCMbQbVilo-nezMvwf1BZfAA'], 'Lahiperactina': ['UCV5G678sZwW5IcF3pCfRbHQ'], 'CdeCiencia': ['UC52hytXteCKmuOzMViTK8_w'], 'codificandobits': ['UCFVF0MpD1lNdU5VL3Pz67Yw'], 'Derivando': ['UCH-Z8ya93m7_RD02WsCSZYA'], 'DateunVoltio': ['UCns-8DssCBba7M4nu7wk7Aw']}


In [ ]:
from googleapiclient.discovery import build
from google.colab import files
import pandas as pd


# Lista para almacenar detalles de canales
data = []

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

for channel_name, channel_id in channelIdName.items():
    # Obtener información del canal
    channel_info = youtube.channels().list(
        part='snippet',
        id=channel_id
    ).execute()

    # Si se encontró información para el canal
    if 'items' in channel_info and len(channel_info['items']) > 0:
        # Obtener detalles del canal
        snippet = channel_info['items'][0]['snippet']
        title = snippet.get('title', '')
        description = snippet.get('description', '')
        published_at = snippet.get('publishedAt', '')

        # Agregar detalles del canal a la lista de datos
        data.append([channel_name, channel_id[0], title, description, published_at, "Ciencia"])

dfCiencia = pd.DataFrame(data, columns=columns)


In [ ]:
from googleapiclient.discovery import build
import json

# Inserta tus credenciales de la API de YouTube aquí
API_KEY = 'AIzaSyDIWwxlFxTsZB9W25eSG3PDglyqbBiXHL8'

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Lista de canales y sus IDs


# Recorrer el DataFrame por filas usando iterrows()
for indice, canal in dfCiencia.iterrows():
    # Obtener los 100 videos más vistos del canal
    videos = []
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video'
    )
    response = request.execute()


    # Agrega los primeros 50 videos a la lista
    videos.extend(response['items'])

#  Verifica si hay una segunda página de resultados
    if 'nextPageToken' in response:
        next_page_token = response['nextPageToken']

    # Realiza una nueva solicitud para obtener los siguientes 50 videos
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video',
        pageToken=next_page_token
    )
    response = request.execute()

    # Agrega los siguientes 50 videos a la lista
    videos.extend(response['items'])
    response = request.execute()
    print("------Procesando : "+canal['Nombre']+" ---------")

    # Estructurar los datos en el formato deseado
    videosData = []

    for item in videos:
        # Obtener los comentarios del video

        video_id = item['id']['videoId']
        comments_request = youtube.commentThreads().list(
            part='snippet',
            videoId=video_id,
            maxResults=15  # Puedes ajustar este número según tus necesidades
        )
        comments_response = comments_request.execute()

        comments = []
        for comment_item in comments_response['items']:
            comment = {
                "user": comment_item['snippet']['topLevelComment']['snippet']['authorDisplayName'],
                "comment": comment_item['snippet']['topLevelComment']['snippet']['textDisplay'],
                "sentiment": ""  # Puedes agregar análisis de sentimiento si lo deseas
            }
            comments.append(comment)

        video_data = {
            "date": item['snippet']['publishedAt'],
            "title": item['snippet']['title'],
            "description": item['snippet']['description'],
            "comments": comments
        }
        videosData.append(video_data)

    # Crear el diccionario con la información del canal y videos
    canal_info = {
        "channel": canal['Nombre'],
        "type": canal['Tipo'],
        "videos": videosData
    }
    print(" Procesados ", len(videosData))


    # Guardar los datos en un archivo JSON
    nombre_archivo = f"{canal['Nombre']}.json"
    with open(nombre_archivo, 'w', encoding='utf-8') as file:
        json.dump(canal_info, file, indent=4, ensure_ascii=False)

------Procesando : QuantumFracture ---------
 Procesados  100
------Procesando : doctorfision ---------
 Procesados  100
------Procesando : ElRobotdePlaton ---------
 Procesados  100
------Procesando : IFTMadrid ---------
 Procesados  100
------Procesando : CienciaDeSofa ---------
 Procesados  100
------Procesando : Lahiperactina ---------
 Procesados  100
------Procesando : CdeCiencia ---------
 Procesados  100
------Procesando : codificandobits ---------
 Procesados  100
------Procesando : Derivando ---------
 Procesados  100
------Procesando : DateunVoltio ---------
 Procesados  100


In [ ]:
from googleapiclient.discovery import build

API_KEY = "AIzaSyB579rVu_fku0ueVHs3LaM_SdbWP7tPsl4"
# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Nombre del canal o URL del canal

channelsNames = ['espndeportes', 'mundomaldini', 'Lamediainglesa', 'Nicfut11', 'premierleague', 'Delantero09', 'LaLiga', 'ProyectoFutbolteca', 'javifreestyle', 'memoriasdelfutbol']
channelIdName = dict()
for name in channelsNames :
  channelIdName[name] = []
  # Utiliza la API de búsqueda para obtener información del canal
  channel_info = youtube.search().list(
                part='snippet',
                maxResults=1,
                q=name,
                type='channel'
        ).execute()

  channel_id = channel_info['items'][0]['id'].get("channelId")
  channelIdName[name].append(channel_id)
print(channelIdName)

{'espndeportes': ['UC08mnbiC4FykqpHqbEWgFcg'], 'mundomaldini': ['UCcrBhhQdWjJjjLyrOvYzMaA'], 'Lamediainglesa': ['UC2V8vo8d3i-XQR-JcrmwwFA'], 'Nicfut11': ['UC7I9AdGpKGe1mKBFAZsFZaw'], 'premierleague': ['UCG5qGWdu8nIRZqJ_GgDwQ-w'], 'Delantero09': ['UCZBJjyp-QbQKvmFkG-ltmvQ'], 'LaLiga': ['UCTv-XvfzLX3i4IGWAm4sbmA'], 'ProyectoFutbolteca': ['UC9KpWygLriBpKk0Vyb3cjLQ'], 'javifreestyle': ['UCDH0QdbNAODoidTx502EDtg'], 'memoriasdelfutbol': ['UCWNv6vx6WOTN91XGT5OHVXg']}


In [ ]:
from googleapiclient.discovery import build
from google.colab import files
import pandas as pd


# Lista para almacenar detalles de canales
data = []



# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

for channel_name, channel_id in channelIdName.items():
    # Obtener información del canal
    channel_info = youtube.channels().list(
        part='snippet',
        id=channel_id
    ).execute()

    # Si se encontró información para el canal
    if 'items' in channel_info and len(channel_info['items']) > 0:
        # Obtener detalles del canal
        snippet = channel_info['items'][0]['snippet']
        title = snippet.get('title', '')
        description = snippet.get('description', '')
        published_at = snippet.get('publishedAt', '')

        # Agregar detalles del canal a la lista de datos
        data.append([channel_name, channel_id[0], title, description, published_at, "Futbol"])

dfFutbol = pd.DataFrame(data, columns=columns)

In [ ]:
from googleapiclient.discovery import build
import json

# Inserta tus credenciales de la API de YouTube aquí
API_KEY = 'AIzaSyB579rVu_fku0ueVHs3LaM_SdbWP7tPsl4'

# Crea un servicio de la API de YouTube
youtube = build('youtube', 'v3', developerKey=API_KEY)

# Lista de canales y sus IDs


# Recorrer el DataFrame por filas usando iterrows()
for indice, canal in dfFutbol.iterrows():
    # Obtener los 100 videos más vistos del canal
    videos = []
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video'
    )
    response = request.execute()


    # Agrega los primeros 50 videos a la lista
    videos.extend(response['items'])

#  Verifica si hay una segunda página de resultados
    if 'nextPageToken' in response:
        next_page_token = response['nextPageToken']

    # Realiza una nueva solicitud para obtener los siguientes 50 videos
    request = youtube.search().list(
        part='snippet',
        channelId=canal["ID"],
        maxResults=50,
        order='viewCount',
        type='video',
        pageToken=next_page_token
    )
    response = request.execute()

    # Agrega los siguientes 50 videos a la lista
    videos.extend(response['items'])
    response = request.execute()
    print("------Procesando : "+canal['Nombre']+" ---------")

    # Estructurar los datos en el formato deseado
    videosData = []

    for item in videos:
        # Obtener los comentarios del video

        video_id = item['id']['videoId']
        comments_request = youtube.commentThreads().list(
            part='snippet',
            videoId=video_id,
            maxResults=15  # Puedes ajustar este número según tus necesidades
        )
        comments_response = comments_request.execute()

        comments = []
        for comment_item in comments_response['items']:
            comment = {
                "user": comment_item['snippet']['topLevelComment']['snippet']['authorDisplayName'],
                "comment": comment_item['snippet']['topLevelComment']['snippet']['textDisplay'],
                "sentiment": ""  # Puedes agregar análisis de sentimiento si lo deseas
            }
            comments.append(comment)

        video_data = {
            "date": item['snippet']['publishedAt'],
            "title": item['snippet']['title'],
            "description": item['snippet']['description'],
            "comments": comments
        }
        videosData.append(video_data)

    # Crear el diccionario con la información del canal y videos
    canal_info = {
        "channel": canal['Nombre'],
        "type": canal['Tipo'],
        "videos": videosData
    }
    print(" Procesados ", len(videosData))


    # Guardar los datos en un archivo JSON
    nombre_archivo = f"{canal['Nombre']}.json"
    with open(nombre_archivo, 'w', encoding='utf-8') as file:
        json.dump(canal_info, file, indent=4, ensure_ascii=False)


------Procesando : espndeportes ---------
 Procesados  100
------Procesando : mundomaldini ---------
 Procesados  100
------Procesando : Lamediainglesa ---------
 Procesados  100
------Procesando : Nicfut11 ---------
 Procesados  100
------Procesando : premierleague ---------
 Procesados  100
------Procesando : Delantero09 ---------
 Procesados  100
------Procesando : LaLiga ---------
 Procesados  100
------Procesando : ProyectoFutbolteca ---------
 Procesados  100
------Procesando : javifreestyle ---------
 Procesados  100
------Procesando : memoriasdelfutbol ---------
 Procesados  100


In [ ]:
from google.colab import files
import os

folder_path = '/content/'

for file in os.listdir(folder_path):
    if file.endswith('.json'):  # Verifica si el archivo es de tipo JSON
        files.download(folder_path + file)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
import pandas as pd
import json
import os
from sklearn.model_selection import train_test_split
folder_path = '/content/'
# Lista para almacenar los datos
data = []

# Leer los archivos JSON y cargar los datos
for file in os.listdir(folder_path):
    if file.endswith('.json'):  # Verifica si el archivo es de tipo JSON
      with open(file, 'r') as json_file:
          json_data = json.load(json_file)
          channel = json_data["channel"]
          type_channel = json_data['type']
          videos = json_data['videos']
          for video in videos:
                  title = video['title']
                  description = video['description']
                  data.append({'Canal': channel, 'Tipo de Canal': type_channel, 'Título': title, 'Descripción': description})

# Crear un DataFrame de Pandas
dfVideos = pd.DataFrame(data)

print(dfVideos)



In [2]:
import pandas as pd


# Identificar los canales únicos para cada tipo de canal
channels_futbol = dfVideos[dfVideos['Tipo de Canal'] == 'Futbol']['Canal'].unique()
channels_podcast = dfVideos[dfVideos['Tipo de Canal'] == 'Podcast']['Canal'].unique()
channels_ciencia = dfVideos[dfVideos['Tipo de Canal'] == 'Ciencia']['Canal'].unique()

# Dividir los canales en entrenamiento y prueba (7 canales para entrenamiento, 3 para prueba)
channels_train_futbol = channels_futbol[:7]
canales_test_futbol = channels_futbol[7:]

channels_train_podcast = channels_podcast[:7]
channels_test_podcast = channels_podcast[7:]

channels_train_ciencia = channels_ciencia[:7]
channels_test_ciencia = channels_ciencia[7:]

# Filtrar los datos para obtener conjuntos separados de entrenamiento y prueba
train_data = dfVideos[(dfVideos['Canal'].isin(channels_train_futbol)) | (dfVideos['Canal'].isin(channels_train_podcast)) | (dfVideos['Canal'].isin(channels_train_ciencia)) ]
test_data = dfVideos[(dfVideos['Canal'].isin(canales_test_futbol)) | (dfVideos['Canal'].isin(channels_test_podcast)) | (dfVideos['Canal'].isin(channels_test_ciencia))]

# Verificar la distribución de canales en los conjuntos de entrenamiento y prueba
print("Canales en datos de entrenamiento:")
print(train_data['Canal'].value_counts())

print("\nCanales en datos de prueba:")
print(test_data['Canal'].value_counts())


Canales en datos de entrenamiento:
Laplacitaamarilla     100
Derivando             100
Lahiperactina         100
premierleague         100
LaLiga                100
TheWildProject        100
Loquetudigas          100
QuantumFracture       100
DateunVoltio          100
spicy4tuna            100
offsiders.project     100
codificandobits       100
doctorfision          100
NUDEPROJECT           100
worldcast_            100
Delantero09           100
Lamediainglesa        100
ProyectoFutbolteca    100
IFTMadrid             100
javifreestyle         100
memoriasdelfutbol     100
Name: Canal, dtype: int64

Canales en datos de prueba:
EclecticosWorldwide    100
CienciaDeSofa          100
SMAE_Podcast           100
tengounplanpodcast     100
Nicfut11               100
mundomaldini           100
ElRobotdePlaton        100
CdeCiencia             100
espndeportes           100
Name: Canal, dtype: int64


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier


def train_vec_models(xEntrenamiento, xPred, test, yPred) :
    # Vectorización de texto
    vectorizer = TfidfVectorizer()
    X_train_vec = vectorizer.fit_transform(xEntrenamiento)
    X_test_vec = vectorizer.transform(test)

    # Definir varios modelos
    models = {
        'Random Forest': RandomForestClassifier(),
        'SVM': SVC(),
        'Naive Bayes': MultinomialNB(),
        'Logistic Regression': LogisticRegression(),
        'Gradient Boosting Machine': GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, max_depth=3, random_state=42)
    }

    # Entrenamiento y evaluación de varios modelos
    for name, model in models.items():
        print(f"Entrenando modelo: {name}")
        model.fit(X_train_vec, xPred)

        # Predicciones
        y_pred = model.predict(X_test_vec)

        # Evaluación del modelo
        accuracy = accuracy_score(yPred, y_pred)
        print(f"Precisión del modelo {name}: {accuracy}")

        conf_matrix = confusion_matrix(yPred, y_pred)
        print(f"Matriz de Confusión {name}:\n{conf_matrix}")

        class_report = classification_report(yPred, y_pred)
        print(f"Reporte de Clasificación {name}:\n{class_report}")
        print("--------------------------------------------------")



In [ ]:
train_vec_models(train_data['Descripción'], train_data['Tipo de Canal'], test_data['Descripción'], test_data['Tipo de Canal'])

Entrenando modelo: Random Forest
Precisión del modelo Random Forest: 0.6822222222222222
Matriz de Confusión Random Forest:
[[216  30  54]
 [ 89 153  58]
 [ 46   9 245]]
Reporte de Clasificación Random Forest:
              precision    recall  f1-score   support

     Ciencia       0.62      0.72      0.66       300
      Futbol       0.80      0.51      0.62       300
     Podcast       0.69      0.82      0.75       300

    accuracy                           0.68       900
   macro avg       0.70      0.68      0.68       900
weighted avg       0.70      0.68      0.68       900

--------------------------------------------------
Entrenando modelo: SVM
Precisión del modelo SVM: 0.6855555555555556
Matriz de Confusión SVM:
[[222  38  40]
 [ 69 182  49]
 [ 61  26 213]]
Reporte de Clasificación SVM:
              precision    recall  f1-score   support

     Ciencia       0.63      0.74      0.68       300
      Futbol       0.74      0.61      0.67       300
     Podcast       0.71    

In [ ]:
import transformers
from transformers import AutoModelForSequenceClassification

path_sentiment_model = 'finiteautomata/beto-sentiment-analysis'

# Obtenemos el tokenizer
tokenizer = transformers.AutoTokenizer.from_pretrained (path_sentiment_model)
# Obtenemos el modelo para análisis de sentimientos que tiene 3 etiquetas: positivo, negativo y neutro
sentiment_model = AutoModelForSequenceClassification.from_pretrained(path_sentiment_model)




In [ ]:
import torch
import os

folder_path = '/content/'
# Leer los archivos JSON y cargar los datos
for file in os.listdir(folder_path):
    if file.endswith('.json'):  # Verifica si el archivo es de tipo JSON
      with open(file, 'r', encoding="utf-8") as json_file:
          print(json_file)
          json_data = json.load(json_file)
          videos = json_data['videos']
          videos_data = []
          for video in videos:
            comments = []
            for comment in video["comments"]:
                inputs = tokenizer(comment['comment'], return_tensors="pt", truncation=True, padding=True)
                with torch.no_grad():
                  logits = sentiment_model(**inputs).logits
                predicted_class_id = logits.argmax().item()
                prediction= sentiment_model.config.id2label[predicted_class_id]
                comment = {
                    "user": comment["user"],
                    "comment": comment["comment"],
                    "sentiment": prediction  # Puedes agregar análisis de sentimiento si lo deseas
                }
                comments.append(comment)
            video_data = {
            "date": video["date"],
            "title": video["title"],
            "description": video["description"],
            "comments": comments
            }
            videos_data.append(video_data)

    # Crear el diccionario con la información del canal y videos
          canal_info = {
            "channel": json_data['channel'],
            "type": json_data['type'],
            "videos": videos_data
        }

    # Guardar los datos en un archivo JSON
      with open(file, 'w', encoding='utf-8') as fwrite:
          json.dump(canal_info, fwrite, indent=4, ensure_ascii=False)


In [ ]:
from google.colab import files
import os

folder_path = '/content/'

for file in os.listdir(folder_path):
    if file.endswith('.json'):  # Verifica si el archivo es de tipo JSON
        files.download(folder_path + file)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
import pandas as pd


# Agrupar por 'Canal' y 'Tipo de Canal', concatenando las descripciones
result = dfVideos.groupby(['Canal', 'Tipo de Canal']).agg({'Descripción': ' '.join}).reset_index()

# Seleccionar solo las columnas necesarias en el nuevo DataFrame
result = result[['Canal', 'Tipo de Canal', 'Descripción']]

# Identificar los canales únicos para cada tipo de canal
channels_futbol_desc = result[result['Tipo de Canal'] == 'Futbol']['Descripción'].unique()
channels_podcast_desc = result[result['Tipo de Canal'] == 'Podcast']['Descripción'].unique()
channels_ciencia_desc = result[result['Tipo de Canal'] == 'Ciencia']['Descripción'].unique()

channels_futbol_desc = pd.DataFrame(channels_futbol_desc)
channels_podcast_desc = pd.DataFrame(channels_podcast_desc)
channels_ciencia_desc = pd.DataFrame(channels_ciencia_desc)

print(channels_futbol_desc)


                                                   0
0  Niño de 7 años me reta 1vs1 en fútbol ft. Will...
1  El FC Barcelona golea en el Benito Villamarín ...
2  No olvides suscribirte a nuestro canal si no q...
3   Técnica para tirar con curva/ efecto. Mejorar...
4  Esta es la historia de Mágico González, uno de...
5  Saúl Canelo Álvarez y Caleb Plant no pudieron ...
6  Me enfrento al robokeeper, esa máquina que hac...
7  Ya puedes Comprar MI LIBRO sobre la Copa del M...
8  Argentina es campeona del mundo tras una final...
9  Fantastic build-up play from Manchester City m...


In [ ]:
# Instalamos la librería Fasttext y descargamos el modelo preentrenado para el español en binario
!pip3 install fasttext
import fasttext

In [ ]:
!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.es.300.bin.gz
!gzip -d cc.es.300.bin.gz

--2023-12-28 09:55:38--  https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.es.300.bin.gz
Resolving dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)... 3.162.163.34, 3.162.163.19, 3.162.163.51, ...
Connecting to dl.fbaipublicfiles.com (dl.fbaipublicfiles.com)|3.162.163.34|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4500107671 (4.2G) [application/octet-stream]
Saving to: ‘cc.es.300.bin.gz’

cc.es.300.bin.gz    100%[===================>]   4.19G  53.7MB/s    in 82s     

2023-12-28 09:57:00 (52.1 MB/s) - ‘cc.es.300.bin.gz’ saved [4500107671/4500107671]



In [ ]:
ft_model = fasttext.load_model("cc.es.300.bin")

In [ ]:
# Esta función calcula en un único vector de dimensión 300 la media aritmética de todos los vectores de tokens
# de un array de textos dado.
import nltk
nltk.download('stopwords')
nltk.download('punkt')

def gensim_sentence_embeddings(textos, model, idiomaStopWords):
    import nltk
    from nltk.corpus import stopwords
    from gensim.test.utils import datapath
    import unicodedata
    from tqdm import tqdm
    import gensim
    import multiprocessing
    import random
    import numpy as np
#esta función devuelve los sentence embeddings de todos los textos enviados como parámetros
    stopwords_list=stopwords.words(idiomaStopWords)
    sentence_embeddings = []
    for linea in textos:
        line_vec = []
        tokenized_sentence = nltk.tokenize.word_tokenize(linea)
        count = 0
        for token in tokenized_sentence:
           if (token not in stopwords_list):
            # Solamente calculamos los vectores de lo que no son stopwords
            if model.has_index_for(token):
              a = model.get_vector(token)
              if len(line_vec) == 0 :
                line_vec = a
              else:
                line_vec = line_vec + a
              count = count + 1
        if(count>0):
          sentence_embeddings.append(line_vec/count)
        else:
          sentence_embeddings.append(np.zeros(300))
    return sentence_embeddings

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
# Calculamos la similitud usando sentence embeddings
import pandas as pd

# Calculamos la similitud usando sentence embeddings
fasttext_sentence_embeddings = channels_futbol_desc[0].apply(lambda x: ft_model.get_sentence_vector(x))
fasttext_sentence_embeddings = fasttext_sentence_embeddings.to_list()
import numpy as np

import scipy.sparse as sp
if not sp.issparse(fasttext_sentence_embeddings):
            fasttext_sentence_embeddings = sp.csr_matrix(fasttext_sentence_embeddings, dtype=np.float64)

results = []
for i in range(10):
# Calculamos la similitud de los documentos con el coseno para sentence embeddings
  result_i = cosine_similarity(fasttext_sentence_embeddings,fasttext_sentence_embeddings[i]).reshape(-1,) # Op -- (n_docs,1) -- Cosine Sim with each
  results.append(result_i)

results_matrix = np.array(results)
print(results_matrix)



[[1.         0.82162251 0.93146778 0.87647732 0.94603197 0.94810025
  0.94219969 0.92044382 0.94644356 0.58988276]
 [0.82162251 1.         0.71448852 0.67239751 0.72808759 0.79349465
  0.72822403 0.82392628 0.78029499 0.86866419]
 [0.93146778 0.71448852 1.         0.93478632 0.9727245  0.93942529
  0.96530741 0.85319354 0.96333477 0.47779561]
 [0.87647732 0.67239751 0.93478632 1.         0.91624741 0.85615832
  0.94396598 0.77096338 0.88499245 0.46645903]
 [0.94603197 0.72808759 0.9727245  0.91624741 1.         0.94088286
  0.95966322 0.85659811 0.95197692 0.49303124]
 [0.94810025 0.79349465 0.93942529 0.85615832 0.94088286 1.
  0.9293059  0.89747676 0.97076104 0.53583435]
 [0.94219969 0.72822403 0.96530741 0.94396598 0.95966322 0.9293059
  1.         0.8321251  0.95436197 0.48695376]
 [0.92044382 0.82392628 0.85319354 0.77096338 0.85659811 0.89747676
  0.8321251  1.         0.87958889 0.61031586]
 [0.94644356 0.78029499 0.96333477 0.88499245 0.95197692 0.97076104
  0.95436197 0.879588

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
# Calculamos la similitud usando sentence embeddings
import pandas as pd


# Calculamos la similitud usando sentence embeddings
fasttext_sentence_embeddings = channels_ciencia_desc[0].apply(lambda x: ft_model.get_sentence_vector(x))
fasttext_sentence_embeddings = fasttext_sentence_embeddings.to_list()
import numpy as np

import scipy.sparse as sp
if not sp.issparse(fasttext_sentence_embeddings):
            fasttext_sentence_embeddings = sp.csr_matrix(fasttext_sentence_embeddings, dtype=np.float64)

results = []
for i in range(10):
# Calculamos la similitud de los documentos con el coseno para sentence embeddings
  result_i = cosine_similarity(fasttext_sentence_embeddings,fasttext_sentence_embeddings[i]).reshape(-1,) # Op -- (n_docs,1) -- Cosine Sim with each
  results.append(result_i)

results_matrix = np.array(results)
print(results_matrix)

[[1.         0.95666647 0.98560438 0.97768671 0.98985096 0.96912955
  0.98192265 0.98338113 0.59621891 0.98277408]
 [0.95666647 1.         0.96765261 0.96123277 0.96030768 0.96238932
  0.965271   0.9480092  0.58772722 0.95567717]
 [0.98560438 0.96765261 1.         0.98577651 0.98700641 0.97893236
  0.98546746 0.98583911 0.56746914 0.98239982]
 [0.97768671 0.96123277 0.98577651 1.         0.98255239 0.96757371
  0.97911458 0.97761237 0.57680826 0.97616227]
 [0.98985096 0.96030768 0.98700641 0.98255239 1.         0.96840622
  0.98123543 0.9847477  0.60266819 0.98592833]
 [0.96912955 0.96238932 0.97893236 0.96757371 0.96840622 1.
  0.97067715 0.95640423 0.58304783 0.95949885]
 [0.98192265 0.965271   0.98546746 0.97911458 0.98123543 0.97067715
  1.         0.97770416 0.58516956 0.975964  ]
 [0.98338113 0.9480092  0.98583911 0.97761237 0.9847477  0.95640423
  0.97770416 1.         0.59461897 0.98440707]
 [0.59621891 0.58772722 0.56746914 0.57680826 0.60266819 0.58304783
  0.58516956 0.59461

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
# Calculamos la similitud usando sentence embeddings
import pandas as pd


# Calculamos la similitud usando sentence embeddings
fasttext_sentence_embeddings = channels_podcast_desc[0].apply(lambda x: ft_model.get_sentence_vector(x))
fasttext_sentence_embeddings = fasttext_sentence_embeddings.to_list()
import numpy as np

import scipy.sparse as sp
if not sp.issparse(fasttext_sentence_embeddings):
            fasttext_sentence_embeddings = sp.csr_matrix(fasttext_sentence_embeddings, dtype=np.float64)

results = []
for i in range(10):
# Calculamos la similitud de los documentos con el coseno para sentence embeddings
  result_i = cosine_similarity(fasttext_sentence_embeddings,fasttext_sentence_embeddings[i]).reshape(-1,) # Op -- (n_docs,1) -- Cosine Sim with each
  results.append(result_i)

results_matrix = np.array(results)
print(results_matrix)


[[1.         0.87550783 0.93170044 0.89115588 0.75431769 0.93787132
  0.93593109 0.75716682 0.8439466  0.88791098]
 [0.87550783 1.         0.90998589 0.88738002 0.83440052 0.91417673
  0.8785485  0.70698517 0.85371218 0.86582557]
 [0.93170044 0.90998589 1.         0.88295157 0.78780293 0.96045475
  0.9345476  0.76247701 0.84390296 0.87848355]
 [0.89115588 0.88738002 0.88295157 1.         0.78056147 0.90641822
  0.88291137 0.74912085 0.85428723 0.84255033]
 [0.75431769 0.83440052 0.78780293 0.78056147 1.         0.82216029
  0.74885062 0.76450614 0.84161802 0.78184465]
 [0.93787132 0.91417673 0.96045475 0.90641822 0.82216029 1.
  0.9307493  0.80622613 0.88449305 0.88879034]
 [0.93593109 0.8785485  0.9345476  0.88291137 0.74885062 0.9307493
  1.         0.75050388 0.81942987 0.85935195]
 [0.75716682 0.70698517 0.76247701 0.74912085 0.76450614 0.80622613
  0.75050388 1.         0.80992659 0.74176121]
 [0.8439466  0.85371218 0.84390296 0.85428723 0.84161802 0.88449305
  0.81942987 0.809926

OPTATIVOS:
**5.1**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

# Crear representaciones vectoriales para unigramas, bigramas y trigramas
vectorizer_unigrams = TfidfVectorizer(ngram_range=(1, 1))
vectorizer_bigrams = TfidfVectorizer(ngram_range=(2, 2))
vectorizer_trigrams = TfidfVectorizer(ngram_range=(3, 3))

X_train_unigrams = vectorizer_unigrams.fit_transform(train_data['Descripción'])
X_train_bigrams = vectorizer_bigrams.fit_transform(train_data['Descripción'])
X_train_trigrams = vectorizer_trigrams.fit_transform(train_data['Descripción'])

# Transformar datos de prueba con las mismas características
X_test_unigrams = vectorizer_unigrams.transform(test_data['Descripción'])
X_test_bigrams = vectorizer_bigrams.transform(test_data['Descripción'])
X_test_trigrams = vectorizer_trigrams.transform(test_data['Descripción'])

# Entrenar modelos con diferentes características
model_unigrams = SVC()
model_bigrams = SVC()
model_trigrams = SVC()


model_unigrams.fit(X_train_unigrams, train_data['Tipo de Canal'])
model_bigrams.fit(X_train_bigrams, train_data['Tipo de Canal'])
model_trigrams.fit(X_train_trigrams, train_data['Tipo de Canal'])



# Evaluar modelos en datos de prueba
y_pred_unigrams = model_unigrams.predict(X_test_unigrams)
y_pred_bigrams = model_bigrams.predict(X_test_bigrams)
y_pred_trigrams = model_trigrams.predict(X_test_trigrams)

  # Evaluación del modelo
name = "SVM"
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Precisión del modelo de unigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Matriz de Confusión unigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Reporte de Clasificación unigramas {name}:\n{class_report}")
print("--------------------------------------------------")


# Evaluación del modelo
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Precisión del modelo de bigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Matriz de Confusión bigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Reporte de Clasificación bigramas {name}:\n{class_report}")
print("--------------------------------------------------")
#Evaluación del modelo
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Precisión del modelo de trigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Matriz de Confusión trigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Reporte de Clasificación trigramas {name}:\n{class_report}")
print("--------------------------------------------------")



Precisión del modelo de unigramas SVM: 0.6855555555555556
Matriz de Confusión unigramas SVM:
[[222  38  40]
 [ 69 182  49]
 [ 61  26 213]]
Reporte de Clasificación unigramas SVM:
              precision    recall  f1-score   support

     Ciencia       0.63      0.74      0.68       300
      Futbol       0.74      0.61      0.67       300
     Podcast       0.71      0.71      0.71       300

    accuracy                           0.69       900
   macro avg       0.69      0.69      0.69       900
weighted avg       0.69      0.69      0.69       900

--------------------------------------------------
Precisión del modelo de bigramas SVM: 0.6733333333333333
Matriz de Confusión bigramas SVM:
[[242  26  32]
 [ 67 182  51]
 [ 89  29 182]]
Reporte de Clasificación bigramas SVM:
              precision    recall  f1-score   support

     Ciencia       0.61      0.81      0.69       300
      Futbol       0.77      0.61      0.68       300
     Podcast       0.69      0.61      0.64       

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

# Crear representaciones vectoriales para unigramas, bigramas y trigramas
vectorizer_unigrams = TfidfVectorizer(ngram_range=(1, 1))
vectorizer_bigrams = TfidfVectorizer(ngram_range=(2, 2))
vectorizer_trigrams = TfidfVectorizer(ngram_range=(3, 3))

X_train_unigrams = vectorizer_unigrams.fit_transform(train_data['Descripción'])
X_train_bigrams = vectorizer_bigrams.fit_transform(train_data['Descripción'])
X_train_trigrams = vectorizer_trigrams.fit_transform(train_data['Descripción'])

# Transformar datos de prueba con las mismas características
X_test_unigrams = vectorizer_unigrams.transform(test_data['Descripción'])
X_test_bigrams = vectorizer_bigrams.transform(test_data['Descripción'])
X_test_trigrams = vectorizer_trigrams.transform(test_data['Descripción'])

# Entrenar modelos con diferentes características
model_unigrams = RandomForestClassifier()
model_bigrams = RandomForestClassifier()
model_trigrams = RandomForestClassifier()


model_unigrams.fit(X_train_unigrams, train_data['Tipo de Canal'])
model_bigrams.fit(X_train_bigrams, train_data['Tipo de Canal'])
model_trigrams.fit(X_train_trigrams, train_data['Tipo de Canal'])



# Evaluar modelos en datos de prueba
y_pred_unigrams = model_unigrams.predict(X_test_unigrams)
y_pred_bigrams = model_bigrams.predict(X_test_bigrams)
y_pred_trigrams = model_trigrams.predict(X_test_trigrams)

  # Evaluación del modelo
name = "RandomForestClassifier"
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Precisión del modelo de unigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Matriz de Confusión unigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Reporte de Clasificación unigramas {name}:\n{class_report}")
print("--------------------------------------------------")


# Evaluación del modelo
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Precisión del modelo de bigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Matriz de Confusión bigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Reporte de Clasificación bigramas {name}:\n{class_report}")
print("--------------------------------------------------")
#Evaluación del modelo
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Precisión del modelo de trigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Matriz de Confusión trigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Reporte de Clasificación trigramas {name}:\n{class_report}")
print("--------------------------------------------------")

Precisión del modelo de unigramas RandomForestClassifier: 0.6622222222222223
Matriz de Confusión unigramas RandomForestClassifier:
[[216  26  58]
 [ 92 145  63]
 [ 59   6 235]]
Reporte de Clasificación unigramas RandomForestClassifier:
              precision    recall  f1-score   support

     Ciencia       0.59      0.72      0.65       300
      Futbol       0.82      0.48      0.61       300
     Podcast       0.66      0.78      0.72       300

    accuracy                           0.66       900
   macro avg       0.69      0.66      0.66       900
weighted avg       0.69      0.66      0.66       900

--------------------------------------------------
Precisión del modelo de bigramas RandomForestClassifier: 0.5377777777777778
Matriz de Confusión bigramas RandomForestClassifier:
[[135   7 158]
 [ 59  86 155]
 [ 36   1 263]]
Reporte de Clasificación bigramas RandomForestClassifier:
              precision    recall  f1-score   support

     Ciencia       0.59      0.45      0.51 

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

# Crear representaciones vectoriales para unigramas, bigramas y trigramas
vectorizer_unigrams = TfidfVectorizer(ngram_range=(1, 1))
vectorizer_bigrams = TfidfVectorizer(ngram_range=(2, 2))
vectorizer_trigrams = TfidfVectorizer(ngram_range=(3, 3))

X_train_unigrams = vectorizer_unigrams.fit_transform(train_data['Descripción'])
X_train_bigrams = vectorizer_bigrams.fit_transform(train_data['Descripción'])
X_train_trigrams = vectorizer_trigrams.fit_transform(train_data['Descripción'])

# Transformar datos de prueba con las mismas características
X_test_unigrams = vectorizer_unigrams.transform(test_data['Descripción'])
X_test_bigrams = vectorizer_bigrams.transform(test_data['Descripción'])
X_test_trigrams = vectorizer_trigrams.transform(test_data['Descripción'])

# Entrenar modelos con diferentes características
model_unigrams = MultinomialNB()
model_bigrams = MultinomialNB()
model_trigrams = MultinomialNB()


model_unigrams.fit(X_train_unigrams, train_data['Tipo de Canal'])
model_bigrams.fit(X_train_bigrams, train_data['Tipo de Canal'])
model_trigrams.fit(X_train_trigrams, train_data['Tipo de Canal'])


# Evaluar modelos en datos de prueba
y_pred_unigrams = model_unigrams.predict(X_test_unigrams)
y_pred_bigrams = model_bigrams.predict(X_test_bigrams)
y_pred_trigrams = model_trigrams.predict(X_test_trigrams)

  # Evaluación del modelo
name = "MultinomialNB"
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Precisión del modelo de unigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Matriz de Confusión unigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Reporte de Clasificación unigramas {name}:\n{class_report}")
print("--------------------------------------------------")


# Evaluación del modelo
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Precisión del modelo de bigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Matriz de Confusión bigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Reporte de Clasificación bigramas {name}:\n{class_report}")
print("--------------------------------------------------")
#Evaluación del modelo
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Precisión del modelo de trigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Matriz de Confusión trigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Reporte de Clasificación trigramas {name}:\n{class_report}")
print("--------------------------------------------------")

Precisión del modelo de unigramas MultinomialNB: 0.7088888888888889
Matriz de Confusión unigramas MultinomialNB:
[[251  25  24]
 [103 193   4]
 [ 91  15 194]]
Reporte de Clasificación unigramas MultinomialNB:
              precision    recall  f1-score   support

     Ciencia       0.56      0.84      0.67       300
      Futbol       0.83      0.64      0.72       300
     Podcast       0.87      0.65      0.74       300

    accuracy                           0.71       900
   macro avg       0.76      0.71      0.71       900
weighted avg       0.76      0.71      0.71       900

--------------------------------------------------
Precisión del modelo de bigramas MultinomialNB: 0.6666666666666666
Matriz de Confusión bigramas MultinomialNB:
[[235  32  33]
 [ 93 195  12]
 [102  28 170]]
Reporte de Clasificación bigramas MultinomialNB:
              precision    recall  f1-score   support

     Ciencia       0.55      0.78      0.64       300
      Futbol       0.76      0.65      0.70 

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

# Crear representaciones vectoriales para unigramas, bigramas y trigramas
vectorizer_unigrams = TfidfVectorizer(ngram_range=(1, 1))
vectorizer_bigrams = TfidfVectorizer(ngram_range=(2, 2))
vectorizer_trigrams = TfidfVectorizer(ngram_range=(3, 3))

X_train_unigrams = vectorizer_unigrams.fit_transform(train_data['Descripción'])
X_train_bigrams = vectorizer_bigrams.fit_transform(train_data['Descripción'])
X_train_trigrams = vectorizer_trigrams.fit_transform(train_data['Descripción'])

# Transformar datos de prueba con las mismas características
X_test_unigrams = vectorizer_unigrams.transform(test_data['Descripción'])
X_test_bigrams = vectorizer_bigrams.transform(test_data['Descripción'])
X_test_trigrams = vectorizer_trigrams.transform(test_data['Descripción'])

# Entrenar modelos con diferentes características
model_unigrams = LogisticRegression()
model_bigrams = LogisticRegression()
model_trigrams = LogisticRegression()


model_unigrams.fit(X_train_unigrams, train_data['Tipo de Canal'])
model_bigrams.fit(X_train_bigrams, train_data['Tipo de Canal'])
model_trigrams.fit(X_train_trigrams, train_data['Tipo de Canal'])



# Evaluar modelos en datos de prueba
y_pred_unigrams = model_unigrams.predict(X_test_unigrams)
y_pred_bigrams = model_bigrams.predict(X_test_bigrams)
y_pred_trigrams = model_trigrams.predict(X_test_trigrams)

  # Evaluación del modelo
name = "LogisticRegression"
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Precisión del modelo de unigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Matriz de Confusión unigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Reporte de Clasificación unigramas {name}:\n{class_report}")
print("--------------------------------------------------")


# Evaluación del modelo
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Precisión del modelo de bigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Matriz de Confusión bigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Reporte de Clasificación bigramas {name}:\n{class_report}")
print("--------------------------------------------------")
#Evaluación del modelo
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Precisión del modelo de trigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Matriz de Confusión trigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Reporte de Clasificación trigramas {name}:\n{class_report}")
print("--------------------------------------------------")

Precisión del modelo de unigramas LogisticRegression: 0.6966666666666667
Matriz de Confusión unigramas LogisticRegression:
[[216  31  53]
 [ 58 176  66]
 [ 48  17 235]]
Reporte de Clasificación unigramas LogisticRegression:
              precision    recall  f1-score   support

     Ciencia       0.67      0.72      0.69       300
      Futbol       0.79      0.59      0.67       300
     Podcast       0.66      0.78      0.72       300

    accuracy                           0.70       900
   macro avg       0.71      0.70      0.69       900
weighted avg       0.71      0.70      0.69       900

--------------------------------------------------
Precisión del modelo de bigramas LogisticRegression: 0.6844444444444444
Matriz de Confusión bigramas LogisticRegression:
[[209  17  74]
 [ 48 163  89]
 [ 42  14 244]]
Reporte de Clasificación bigramas LogisticRegression:
              precision    recall  f1-score   support

     Ciencia       0.70      0.70      0.70       300
      Futbol  

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier

# Crear representaciones vectoriales para unigramas, bigramas y trigramas
vectorizer_unigrams = TfidfVectorizer(ngram_range=(1, 1))
vectorizer_bigrams = TfidfVectorizer(ngram_range=(2, 2))
vectorizer_trigrams = TfidfVectorizer(ngram_range=(3, 3))

X_train_unigrams = vectorizer_unigrams.fit_transform(train_data['Descripción'])
X_train_bigrams = vectorizer_bigrams.fit_transform(train_data['Descripción'])
X_train_trigrams = vectorizer_trigrams.fit_transform(train_data['Descripción'])

# Transformar datos de prueba con las mismas características
X_test_unigrams = vectorizer_unigrams.transform(test_data['Descripción'])
X_test_bigrams = vectorizer_bigrams.transform(test_data['Descripción'])
X_test_trigrams = vectorizer_trigrams.transform(test_data['Descripción'])

# Entrenar modelos con diferentes características
model_unigrams = GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, max_depth=3, random_state=42)
model_bigrams = GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, max_depth=3, random_state=42)
model_trigrams = GradientBoostingClassifier(n_estimators=200, learning_rate=0.1, max_depth=3, random_state=42)


model_unigrams.fit(X_train_unigrams, train_data['Tipo de Canal'])
model_bigrams.fit(X_train_bigrams, train_data['Tipo de Canal'])
model_trigrams.fit(X_train_trigrams, train_data['Tipo de Canal'])


# Evaluar modelos en datos de prueba
y_pred_unigrams = model_unigrams.predict(X_test_unigrams)
y_pred_bigrams = model_bigrams.predict(X_test_bigrams)
y_pred_trigrams = model_trigrams.predict(X_test_trigrams)

  # Evaluación del modelo
name = "GradientBoostingClassifier"
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Precisión del modelo de unigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Matriz de Confusión unigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_unigrams)
print(f"Reporte de Clasificación unigramas {name}:\n{class_report}")
print("--------------------------------------------------")


# Evaluación del modelo
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Precisión del modelo de bigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Matriz de Confusión bigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_bigrams)
print(f"Reporte de Clasificación bigramas {name}:\n{class_report}")
print("--------------------------------------------------")
#Evaluación del modelo
accuracy = accuracy_score(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Precisión del modelo de trigramas {name}: {accuracy}")

conf_matrix = confusion_matrix(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Matriz de Confusión trigramas {name}:\n{conf_matrix}")

class_report = classification_report(test_data['Tipo de Canal'], y_pred_trigrams)
print(f"Reporte de Clasificación trigramas {name}:\n{class_report}")
print("--------------------------------------------------")

Precisión del modelo de unigramas GradientBoostingClassifier: 0.69
Matriz de Confusión unigramas GradientBoostingClassifier:
[[220  22  58]
 [ 86 145  69]
 [ 39   5 256]]
Reporte de Clasificación unigramas GradientBoostingClassifier:
              precision    recall  f1-score   support

     Ciencia       0.64      0.73      0.68       300
      Futbol       0.84      0.48      0.61       300
     Podcast       0.67      0.85      0.75       300

    accuracy                           0.69       900
   macro avg       0.72      0.69      0.68       900
weighted avg       0.72      0.69      0.68       900

--------------------------------------------------
Precisión del modelo de bigramas GradientBoostingClassifier: 0.5766666666666667
Matriz de Confusión bigramas GradientBoostingClassifier:
[[162  28 110]
 [ 58  99 143]
 [ 39   3 258]]
Reporte de Clasificación bigramas GradientBoostingClassifier:
              precision    recall  f1-score   support

     Ciencia       0.63      0.54 

**5.3**

In [33]:
import pandas as pd


# Identificar los canales únicos para cada tipo de canal
channels_futbol = dfVideos[dfVideos['Tipo de Canal'] == 'Futbol']['Canal'].unique()
channels_podcast = dfVideos[dfVideos['Tipo de Canal'] == 'Podcast']['Canal'].unique()
channels_ciencia = dfVideos[dfVideos['Tipo de Canal'] == 'Ciencia']['Canal'].unique()

# Dividir los canales en entrenamiento y prueba (7 canales para entrenamiento, 3 para prueba)
channels_train_futbol = channels_futbol[:6]
channels_eval_futbol = channels_futbol[6:8]
channels_test_futbol = channels_futbol[8:]

channels_train_podcast = channels_podcast[:6]
channels_eval_podcast  = channels_podcast[6:8]
channels_test_podcast  = channels_podcast[8:]

channels_train_ciencia = channels_ciencia[:6]
channels_eval_ciencia= channels_ciencia[6:8]
channels_test_ciencia = channels_ciencia[8:]


# Filtrar los datos para obtener conjuntos separados de entrenamiento y prueba
train_data = dfVideos[(dfVideos['Canal'].isin(channels_train_futbol)) | (dfVideos['Canal'].isin(channels_train_podcast)) | (dfVideos['Canal'].isin(channels_train_ciencia)) ]
eval_data = dfVideos[(dfVideos['Canal'].isin(channels_eval_futbol)) | (dfVideos['Canal'].isin(channels_eval_podcast)) | (dfVideos['Canal'].isin(channels_eval_ciencia))]
test_data = dfVideos[(dfVideos['Canal'].isin(channels_test_futbol)) | (dfVideos['Canal'].isin(channels_test_podcast)) | (dfVideos['Canal'].isin(channels_test_ciencia))]

# Verificar la distribución de canales en los conjuntos de entrenamiento y prueba
print("Canales en datos de entrenamiento:")
print(train_data['Canal'].value_counts())

print("Canales en datos de evaluacion:")
print(eval_data['Canal'].value_counts())

print("\nCanales en datos de prueba:")
print(test_data['Canal'].value_counts())

# Definir un diccionario que mapee las etiquetas a números
label_mapping = {"Futbol": 0, "Podcast": 1, "Ciencia": 2}

# Aplicar la transformación a las etiquetas en los DataFrames
train_data['label'] = train_data['Tipo de Canal'].map(label_mapping)
eval_data['label'] = eval_data['Tipo de Canal'].map(label_mapping)
test_data['label'] = test_data['Tipo de Canal'].map(label_mapping)



Canales en datos de entrenamiento:
Lahiperactina          100
CdeCiencia             100
spicy4tuna             100
Laplacitaamarilla      100
javifreestyle          100
LaLiga                 100
NUDEPROJECT            100
IFTMadrid              100
memoriasdelfutbol      100
Lamediainglesa         100
EclecticosWorldwide    100
DateunVoltio           100
ProyectoFutbolteca     100
doctorfision           100
QuantumFracture        100
mundomaldini           100
offsiders.project      100
SMAE_Podcast           100
Name: Canal, dtype: int64
Canales en datos de evaluacion:
ElRobotdePlaton    100
Delantero09        100
premierleague      100
codificandobits    100
Loquetudigas       100
Name: Canal, dtype: int64

Canales en datos de prueba:
Nicfut11         100
Derivando        100
espndeportes     100
CienciaDeSofa    100
Name: Canal, dtype: int64


<ipython-input-33-665c4390d65c>:42: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_data['label'] = train_data['Tipo de Canal'].map(label_mapping)
<ipython-input-33-665c4390d65c>:43: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eval_data['label'] = eval_data['Tipo de Canal'].map(label_mapping)
<ipython-input-33-665c4390d65c>:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the docu

In [31]:
!pip3 install -U transformers torch datasets




     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.1/507.1 kB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 6.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 7.9 MB/s eta 0:00:00


In [6]:
pip install accelerate -U

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.7/265.7 kB 5.1 MB/s eta 0:00:00


In [7]:
pip install transformers[torch]

In [32]:
import torch
import datasets
import transformers
import tokenizers
from transformers import AutoModelForSequenceClassification,TrainingArguments
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from transformers import AutoTokenizer
from datasets import load_metric





path_bert_model = 'CenIA/distillbert-base-spanish-uncased'
# Cargamos el modelo para clasificación en Pytorch
NUM_LABELS = 3
bert_class_model_pytorch = AutoModelForSequenceClassification.from_pretrained(path_bert_model, num_labels=NUM_LABELS)
# Cargamos el tokenizer de este modelo
tokenizer = AutoTokenizer.from_pretrained(path_bert_model)

# Los datasets se preparan dde manera distinta a Tensorflow
class TGINEDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)


metric = load_metric("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)



from transformers import TrainingArguments

batch_train_size = 16
batch_val_size = 64

# Definimos algunos training arguments como el tamaño del bach_size
training_args = transformers.TrainingArguments (
  output_dir = './results',
  logging_dir = './logs',
  per_device_train_batch_size = batch_train_size,
  per_device_eval_batch_size = batch_val_size
)


tokenized_train_dataset = tokenizer(train_data['Descripción'].tolist(), truncation=True , padding = True)
tokenized_eval_dataset = tokenizer(eval_data['Descripción'].tolist(), truncation=True , padding = True)
tokenized_test_dataset = tokenizer(test_data['Descripción'].tolist(), truncation=True , padding = True)


# Como antes, las etiquetas deben ser numéricas para poder entrenar.
# Preparamos los 3 datasets para hacer el finetuning
train_dataset = TGINEDataset (tokenized_train_dataset, train_data['label'].tolist())
eval_dataset = TGINEDataset (tokenized_eval_dataset, eval_data['label'].tolist())
test_dataset = TGINEDataset (tokenized_test_dataset, test_data['label'].tolist())

from transformers import Trainer

trainer = Trainer (
    model = bert_class_model_pytorch,
    args = training_args,
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    compute_metrics = compute_metrics,
)
trainer.train()


print ("PREDICCIONES SOBRE EVAL")
bert_class_model_pytorch.eval ()
print (json.dumps (trainer.evaluate (), indent = 2))


# Salvamos el modelo reentrenado
modelo ='modeloReentrenadoPytorch'
bert_class_model_pytorch.save_pretrained (modelo)
tokenizer.save_pretrained (modelo)

print ("PREDICCIONES SOBRE TEST")
predictions = trainer.predict (test_dataset)
print(json.dumps(predictions.metrics, indent = 2))

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at CenIA/distillbert-base-spanish-uncased and are newly initialized: ['classifier.weight', 'classifier.bias', 'pre_classifier.weight', 'pre_classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
<ipython-input-32-dfabb5d9fe28>:37: FutureWarning: load_metric is deprecated and will be removed in the next major version of datasets. Use 'evaluate.load' instead, from the new library 🤗 Evaluate: https://huggingface.co/docs/evaluate
  metric = load_metric("accuracy")
/usr/local/lib/python3.10/dist-packages/datasets/load.py:752: FutureWarning: The repository for accuracy contains custom code which must be executed to correctly load the metric. You can inspect the repository content at https://raw.githubusercontent.com/huggingface/datasets/2.16.0/metrics/accuracy/accuracy.py
You can avoid this message in future by passing th

PREDICCIONES SOBRE EVAL


{
  "eval_loss": 0.36031556129455566,
  "eval_accuracy": 0.918,
  "eval_runtime": 1.5254,
  "eval_samples_per_second": 327.775,
  "eval_steps_per_second": 5.244,
  "epoch": 3.0
}
PREDICCIONES SOBRE TEST
{
  "test_loss": 0.9863392114639282,
  "test_accuracy": 0.7925,
  "test_runtime": 0.7684,
  "test_samples_per_second": 520.56,
  "test_steps_per_second": 9.11
}
